code: regex-with-python
title: Regex With Python
toc:
  - code: regex-introduction
    title: Regex Introduction
    id: 6100db06-9273-48b2-ae5e-0074bfbd11ee
    topics: []
  - code: about
    title: About
    id: 53cb429e-bd27-46d6-a657-c1f04138ae22
    topics:
      - code: book
        title: Book
        id: 4b6c3d8d-a13e-4d50-a1f2-68e946b6f857
      - code: author
        title: Author
        id: b1a7f1b9-2311-4812-9927-97b4e75dcac3
