code: regex-with-python
title: Regex With Python
toc:
  - code: regex-introduction
    title: Regex Introduction
    id: 6100db06-9273-48b2-ae5e-0074bfbd11ee
    topics:
      - code: introduction
        title: Introduction
        id: fceb85d2-9058-4475-97dc-1c79c47ce8e2
      - code: setting-the-stage-1
        title: Setting The Stage
        id: 35c59dbd-721b-48ed-8e31-3292dab5b1a2
      - code: problem-statement
        title: Problem Statement
        id: 3b5a273f-52d1-4dcb-a87a-0ce169fe70cf
      - code: gibberish-to-rescue
        title: Gibberish To Rescue
        id: 89e50644-f738-47e6-ac67-e6db5d00c6b8
      - code: the-plan
        title: The Plan
        id: 57fa5634-4e17-4f49-81a1-e4e1ce48d153
  - code: matching-characters
    title: Matching Characters
    id: 11790329-df2c-414e-9de3-c63055bbd0f0
    topics:
      - code: introduction-1
        title: Introduction
        id: 67305f70-7b13-42c2-a2dc-f738dc9644e6
      - code: matching-literals
        title: Matching Literals
        id: 5845ded8-9efd-4416-9126-4a89146fbd2f
      - code: matching-special-characters
        title: Matching Special Characters
        id: 24787453-2095-496d-9584-9b9bdc954853
      - code: matching-this-or-that-1
        title: Matching This or That
        id: e9af1088-37ef-4614-9a93-bd680cf2114f
      - code: matching-one-of-many-characters
        title: Matching One of Many Characters
        id: b6b591cd-2e87-45e2-b419-3c601041741d
      - code: matching-character-types
        title: Matching Character Types
        id: cc4b0ce4-327d-4f5c-8ba5-037784352ad9
  - code: matching-repetitions
    title: Matching Repetitions
    id: 130a68d2-b085-4733-a186-34526d607335
    topics:
      - code: introduction-2
        title: Introduction
        id: 25d6d05b-0d91-4a09-95c9-f5863f949d9c
      - code: matching-m-to-n-occurrences
        title: Matching m To n Occurrences
        id: 51c1ff9c-61bf-466a-b5a9-5e7013576ef5
      - code: matching-0-or-1-occurrences
        title: Matching 0 or 1 Occurrences
        id: af8d9775-90b4-4be6-9ed2-bc60a67e42d8
      - code: matching-0-or-more-occurrences
        title: Matching 0 or More Occurrences
        id: 35eaf227-1125-41db-b91b-c01c80578fd7
      - code: matching-1-or-more-occurrences
        title: Matching 1 or More Occurrences
        id: f21ebec9-1c5c-4927-bc77-304cbf878811
  - code: matching-boundaries
    title: Matching Boundaries
    id: 9e12c308-f9d6-4270-9a3b-800331c1ab3b
    topics:
      - code: introduction-3
        title: Introduction
        id: 1aca0807-ddc5-4d43-8e3b-7d18e2ee58cd
      - code: matching-word-boundaries
        title: Matching Word Boundaries
        id: 0e884287-d7dc-4c31-84e2-a701f6418fbb
  - code: about
    title: About
    id: 53cb429e-bd27-46d6-a657-c1f04138ae22
    topics:
      - code: book
        title: Book
        id: 4b6c3d8d-a13e-4d50-a1f2-68e946b6f857
      - code: author
        title: Author
        id: b1a7f1b9-2311-4812-9927-97b4e75dcac3
